# Generated by Django 2.2.1 on 2019-07-28 18:48

import directory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of the folder', max_length=100)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(help_text='Enter username of creator of folder', max_length=100)),
                ('full_path', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of the file', max_length=100)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(help_text='Enter username of creator of file', max_length=100)),
                ('upload_path', models.FileField(editable=False, upload_to=directory.models.File.get_path)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Folder')),
            ],
        ),
    ]
