# Generated by Django 2.2.1 on 2019-07-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='full_path',
        ),
    ]
