# Generated by Django 2.2.1 on 2019-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_remove_folder_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='full_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
