# Generated by Django 2.2.1 on 2019-07-29 02:29

import directory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20190728_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_path',
            field=models.FileField(upload_to=directory.models.File.get_path),
        ),
    ]
