# Generated by Django 2.2.1 on 2019-07-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20190728_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='full_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
